jobs:
  build:
    name: build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Setup JAVA
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '.mvn/wrapper/maven-wrapper.properties')
          }}
        path: '~/.m2/repository

          ~/.m2/wrapper

          '
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      name: Build
      run: ./mvnw --batch-mode --no-transfer-progress --show-version --settings .github/maven/settings.xml
        verify
    - continue-on-error: true
      name: Test Jackson 2.12.x
      run: ./mvnw --batch-mode --no-transfer-progress --show-version --settings .github/maven/settings.xml
        -Pcompat-jackson surefire:test
    - continue-on-error: true
      if: ${{ always() }}
      name: Upload Test Reports to Github
      uses: actions/upload-artifact@v3
      with:
        if-no-files-found: ignore
        name: test-reports-${{ matrix.java }}
        path: '**/target/surefire-reports/**'
    - continue-on-error: true
      if: matrix.java == '17'
      name: Upload Test Coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: target/site/jacoco/jacoco.xml
    strategy:
      fail-fast: false
      matrix:
        java:
        - '11'
        - '17'
  release:
    if: github.event_name == 'push' && github.repository == 'logfellow/logstash-logback-encoder'
      && github.ref == 'refs/heads/main' && startsWith(github.event.commits[0].message,
      '[release]')
    name: release
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout Code
      uses: actions/checkout@v3
      with:
        ref: main
    - continue-on-error: true
      name: Setup JAVA
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      env:
        GPG_KEY: ${{ secrets.GPG_KEY }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      name: Setup GPG
      run: .github/workflows/steps/setup-gpg.sh
    - continue-on-error: true
      name: Setup GIT
      run: '.github/workflows/steps/setup-git.sh

        git switch main

        '
    - continue-on-error: true
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml', '.mvn/wrapper/maven-wrapper.properties')
          }}
        path: '~/.m2/repository

          ~/.m2/wrapper

          '
        restore-keys: '${{ runner.os }}-maven-

          '
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
      name: Release
      run: ./mvnw --batch-mode --no-transfer-progress --show-version --settings .github/maven/settings.xml
        --activate-profiles ossrh release:prepare release:perform
name: build
on:
  repository_dispatch:
    types: trigger-ga___build.yml
