jobs:
  noResponse:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: lee-dohm/no-response@v0.5.0
      with:
        responseRequiredLabel: status/waiting-for-feedback
        token: ${{ github.token }}
name: no-response
on:
  repository_dispatch:
    types: trigger-ga___no-response.yml
